### ISSUE TITLE
Query Command

### ISSUE THREAD

**Issue by macjeff** [danielcaldentey/udi-netatmo#1]
Can you add query command to program

set   Netatmonodeserver   to Query

its needed in one of my programs.  The other nodeservers have it but yours does not

thanks!!!

**Comment by danielcaldentey** [comment]
Hi Macjeff,

That should be fairly easy. I will try to work on it this weekend.

Aside from this, is the NodeServer working fine for you?

Dani

**Comment by danielcaldentey** [comment]
Hi Macjeff,

Done! Version 1.1.0 has been uploaded and should be showing up on the store later today.
